version: "3"

services:
  mysql1:
    container_name: mysql1
    image: mysql:8.4.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3366:3306"
    volumes:
      - ./mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql1/datadir:/var/lib/mysql

  node1:
    depends_on:
      - mysql1
    environment:
      LOG_LEVEL: "info"
      LOG_FORMAT: "console"
      MYSQL_DATA_SOURCE: "root:root@tcp(mysql1:3306)/abe_committer?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true"
      MYSQL_MAX_IDLE_CONNS: "10"
      MYSQL_MAX_OPEN_CONNS: "20"
      MYSQL_CONN_MAX_LIFETIME: "3600"
      RPC_URL: "http://159.138.106.168:8545"
      BLOCKCHAIN: "abe-node"
      INIT_BLOCK_NUMBER: "300"
      INIT_BLOCK_HASH: "0x0c4408fab90dae9ee884f255ba647aabd387182809f43aa416fd2d255b0f7c4f"
      POLYGON_ZKEVM_ADDRESS: "0xBEfc6B93f8987758231f2381B562996deeE963F9"
      PROPOSAL_BATCHES_LIMITNUM: "2"
      INIT_PROPOSAL_ID: "1"
      B2NODE_PRIVATE_KEY: "8623eb1173b001788b7dc789513c34d049a3d02c728b50daae5799fca009e111"
      B2NODE_ADDRESS: "ethm1e7s8kwnlcnd5vk8fx0jrfpy5cn5wfmwakc5azp"
      B2NODE_CHAIN_ID: "ethermint_9000-1"
      B2NODE_GRPC_HOST: "159.138.106.168"
      B2NODE_GRPC_PORT: "9090"
      B2NODE_RPC_URL: "http://159.138.106.168:9090"
      B2NODE_COIN_DENOM: "aphoton"
      BITCOIN_NETWORK_NAME: "signet"
      BITCOIN_PRIVATE_KEY: "L2Wv2kPRs4iJ8zFwQmTPBvrPQY7DS591LdmTEqu4x6GXX4yVDr7h"
      COMMITTER_DESTINATION_ADDRESS: "bc1peuj9pfr4leqnfmem4nrsxl2cqcz2hafw7k6luxzrxcr545fywm3qrsfvtj"
      ENDPOINT : "https://testnet-snode.abelian.info/v1/single-account"
      RPCENDPOINT : "https://testnet-rpc-00.abelian.info"
      USERNAME : "J8y0OnkS2wx9XEgUlW5MqtoRDAQ="
      PASSWORD : "ULlXc/ZMJ375cn6VuSbtU+Y3KGQ="
      APPID : "8b9ca2d7"
      REQUEST_SIGNATURE : "randstring"
      USERID : "abe32f5c9dd67b6f0e11333fc54e4b54d1f05456ea0e2abc6e1459b056271e3de6180f7cca4ca880a8839c72d412987ffd47d7fdca60fce5838bfcbea68dd741146b"
      FROM : "abe32f5c9dd67b6f0e11333fc54e4b54d1f05456ea0e2abc6e1459b056271e3de6180f7cca4ca880a8839c72d412987ffd47d7fdca60fce5838bfcbea68dd741146b"
      RECIPIENT : "abe338491ef250a530f6b1a771d45ae168f81d6a430f20623849e448b870f0f95e13f12ba51bff83497480db944567750e3cf555cd9811db95b848ca93d45c1448d0"
      PRIVATE_KEY : "0000000064a27b5f97581f0eaeb482d09fb963e0e19f73eb476b6de0d9821967abdc8ea9336bf818d3828d94eb2bfca150fec85dccbbc18c6c6d39a3bd2fbb2a5801c525c42815fe86639ad806246bac5810ea820bdd3ce87d0c1718716019aba621cd3507156e8a72e7a41d81615788392dfd42974ead6a229aeebedf448f091e517d85"
      AUTHTOKEN : "8b9ca2d7f0d4d76e17d02f6f5f82e595"

    image: ghcr.io/mindcarver/abe-committer:v0.2



#  mysql2:
#    image: mysql:8.0.28
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#    ports:
#      - "3377:3306"
#    volumes:
#      - ./mysql.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./mysql2/datadir:/var/lib/mysql
#  node2:
#    environment:
#      LOG_LEVEL: "info"
#      LOG_FORMAT: "console"
#      MYSQL_DATA_SOURCE: "root:root@tcp(127.0.0.1:3306)/b2_committer?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true"
#      MYSQL_MAX_IDLE_CONNS: 10
#      MYSQL_MAX_OPEN_CONNS: 20
#      MYSQL_CONN_MAX_LIFETIME: 3600
#      RPC_URL: "http://haven-b2-nodes.bsquared.network"
#      BLOCKCHAIN: "b2-node"
#      INIT_BLOCK_NUMBER: 10
#      POLYGON_ZKEVM_ADDRESS: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933"
#      PROPOSAL_BATCHES_LIMITNUM: 10
#      B2NODE_PRIVATE_KEY_HEX: "5982c7d494163e8ac80a059debcd33856e64e9409e825568be4666458df93875"
#      B2NODE_ADDRESS: "ethm169pg4vapqw2lpevkz3lclhfkkdpzcaeg2sru8m"
#      B2NODE_CHAIN_ID: "ethermint_9000-1"
#      B2NODE_GRPC_HOST: "127.0.0.1"
#      B2NODE_GRPC_PORT: "9090"
#      B2NODE_RPC_URL: "http://localhost:8545"
#      BITCOIN_NETWORK_NAME: "testnet3"
#      BITCOIN_PRIVATE_KEY: "c545a409ff7f2e66b4bc863a59dcccf0f4387668a92152a058446bcb58a57027"
#      COMMITTER_DESTINATION_ADDRESS: "tb1pvhr4e58yatk9uve22rr5umxs0jh9g0j0gtcj0ry2wf23lddhjptsf6c360"
#    image: ${ETHERMINT_IMAGE}


