version: "3"

services:
  mysql1:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3366:3306"
    volumes:
      - ./mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql1/datadir:/var/lib/mysql


#  mysql2:
#    image: mysql:8.0.28
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#    ports:
#      - "3377:3306"
#    volumes:
#      - ./mysql.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./mysql2/datadir:/var/lib/mysql

  node1:
    depends_on:
      - mysql1
    environment:
      LOG_LEVEL: "info"
      LOG_FORMAT: "console"
      MYSQL_DATA_SOURCE: "root:root@tcp(127.0.0.1:3366)/b2_committer?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true"
      MYSQL_MAX_IDLE_CONNS: 10
      MYSQL_MAX_OPEN_CONNS: 20
      MYSQL_CONN_MAX_LIFETIME: 3600
      RPC_URL: "https://habitat-b2-nodes.bsquared.network"
      BLOCKCHAIN: "b2-node"
      INIT_BLOCK_NUMBER: 10
      POLYGON_ZKEVM_ADDRESS: "0xd9571Aaf414b0F51d40D6738813FA4eA782d18B7"
      PROPOSAL_BATCHES_LIMITNUM: 10
      B2NODE_PRIVATE_KEY_HEX: "0cb6df36e675f96b41f33018a66d7ef075fb047e7295ac06c4233c9fd164ae6c"
      B2NODE_ADDRESS: "ethm120w06zgwpa03kwywf9a4rm760x9pnj3l7nz704"
      B2NODE_CHAIN_ID: "ethermint_9000-1"
      B2NODE_GRPC_HOST: "127.0.0.1"
      B2NODE_GRPC_PORT: "9090"
      B2NODE_RPC_URL: "http://localhost:8545"
      BITCOIN_NETWORK_NAME: "testnet3"
      BITCOIN_PRIVATE_KEY: "55968c09fb90a496096bafdeaac0f791f527b17324d1d0e63d3550e68a7b0cc5"
      COMMITTER_DESTINATION_ADDRESS: "tb1ptlp06cp6da4quje623ne8ataf2d4jy80m3jyjqr34c6dp6s5jddqtusute"
    image: ${ETHERMINT_IMAGE}
#
#
#  node2:
#    environment:
#      LOG_LEVEL: "info"
#      LOG_FORMAT: "console"
#      MYSQL_DATA_SOURCE: "root:root@tcp(127.0.0.1:3306)/b2_committer?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true"
#      MYSQL_MAX_IDLE_CONNS: 10
#      MYSQL_MAX_OPEN_CONNS: 20
#      MYSQL_CONN_MAX_LIFETIME: 3600
#      RPC_URL: "http://haven-b2-nodes.bsquared.network"
#      BLOCKCHAIN: "b2-node"
#      INIT_BLOCK_NUMBER: 10
#      POLYGON_ZKEVM_ADDRESS: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933"
#      PROPOSAL_BATCHES_LIMITNUM: 10
#      B2NODE_PRIVATE_KEY_HEX: "5982c7d494163e8ac80a059debcd33856e64e9409e825568be4666458df93875"
#      B2NODE_ADDRESS: "ethm169pg4vapqw2lpevkz3lclhfkkdpzcaeg2sru8m"
#      B2NODE_CHAIN_ID: "ethermint_9000-1"
#      B2NODE_GRPC_HOST: "127.0.0.1"
#      B2NODE_GRPC_PORT: "9090"
#      B2NODE_RPC_URL: "http://localhost:8545"
#      BITCOIN_NETWORK_NAME: "testnet3"
#      BITCOIN_PRIVATE_KEY: "c545a409ff7f2e66b4bc863a59dcccf0f4387668a92152a058446bcb58a57027"
#      COMMITTER_DESTINATION_ADDRESS: "tb1pvhr4e58yatk9uve22rr5umxs0jh9g0j0gtcj0ry2wf23lddhjptsf6c360"
#    image: ${ETHERMINT_IMAGE}


